[package]
name = "yawnoc"
version = "0.1.0"
description = "Native Rust Conway board in Tauri"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
yawnoc-core = { path = "../yawnoc-core" }
